#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

function readAllStdin() {
  return new Promise((resolve, reject) => {
    const chunks = [];
    process.stdin.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    process.stdin.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    process.stdin.on("error", reject);
  });
}

function pickFirstMatch(text, patterns) {
  for (const pattern of patterns) {
    const match = text.match(pattern);
    if (match && match[1] && match[1].trim().length > 0) {
      return match[1].trim();
    }
  }
  return undefined;
}

function buildTaskId(stdinText, parentRequestId) {
  const fromPayload = pickFirstMatch(stdinText, [
    /"taskId"\s*:\s*"([^"]+)"/,
    /"task_id"\s*:\s*"([^"]+)"/
  ]);
  if (fromPayload) {
    return fromPayload;
  }
  if (parentRequestId && parentRequestId.trim().length > 0) {
    return `task-${parentRequestId.trim().slice(0, 8)}`;
  }
  return `task-${Date.now()}`;
}

function buildTitle(stdinText, role, nextRole) {
  const fromPayload = pickFirstMatch(stdinText, [
    /"title"\s*:\s*"([^"]+)"/
  ]);
  if (fromPayload) {
    return fromPayload;
  }
  if (nextRole) {
    return `Flow handoff ${role} -> ${nextRole}`;
  }
  return `Flow completion by ${role}`;
}

async function ensureArtifact(role, summary) {
  const relPath = path.posix.join("docs", "flow_test", `${role}.md`);
  const absPath = path.resolve(process.cwd(), relPath);
  await fs.mkdir(path.dirname(absPath), { recursive: true });
  const content = [
    `# Mock Flow Artifact`,
    ``,
    `- role: ${role}`,
    `- at: ${new Date().toISOString()}`,
    ``,
    summary
  ].join("\n");
  await fs.writeFile(absPath, `${content}\n`, "utf8");
  return relPath;
}

async function postJson(url, body) {
  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body)
  });
  let payload = {};
  try {
    payload = await response.json();
  } catch {
    // ignore response parse failure
  }
  if (!response.ok) {
    const reason = payload && typeof payload === "object" && "error" in payload
      ? String(payload.error)
      : `HTTP ${response.status}`;
    throw new Error(reason);
  }
  return payload;
}

async function main() {
  const stdinText = await readAllStdin();
  const role = (process.env.AUTO_DEV_AGENT_ROLE ?? "unknown").trim() || "unknown";
  const projectId = (process.env.AUTO_DEV_PROJECT_ID ?? "").trim();
  const sessionId = (process.env.AUTO_DEV_SESSION_ID ?? "").trim();
  const parentRequestId = (process.env.AUTO_DEV_PARENT_REQUEST_ID ?? "").trim();
  const managerUrl = (process.env.AUTO_DEV_MANAGER_URL ?? "http://127.0.0.1:3000").trim();

  if (!projectId || !sessionId) {
    throw new Error("AUTO_DEV_PROJECT_ID and AUTO_DEV_SESSION_ID are required");
  }

  const handoffMap = {
    pm_product: "pm_challenger",
    pm_challenger: "eng_manager",
    eng_manager: "engineer",
    engineer: "qa_guard"
  };

  const nextRole = handoffMap[role];
  const taskId = buildTaskId(stdinText, parentRequestId);
  const title = buildTitle(stdinText, role, nextRole);
  const summary = nextRole
    ? `[mock-flow] ${role} analyzed and handed off to ${nextRole}.`
    : `[mock-flow] ${role} completed QA and closed the chain.`;
  const artifactPath = await ensureArtifact(role, summary);

  const reportBody = {
    report_id: `report-${crypto.randomUUID()}`,
    project_id: projectId,
    session_id: sessionId,
    agent_id: role,
    task_id: taskId,
    status: nextRole ? "HANDOFF" : "DONE",
    summary,
    details: `Generated by mock_agent_cli for role=${role}.`,
    artifacts: [
      {
        kind: "doc",
        path: artifactPath,
        note: "mock flow artifact"
      }
    ],
    correlation: {
      request_id: `req-${crypto.randomUUID()}`,
      parent_request_id: parentRequestId || undefined,
      task_id: taskId
    },
    problems: [],
    suggest_next_actions: nextRole
      ? [
          {
            to_role: nextRole,
            type: "ASSIGN_TASK",
            payload: {
              taskId,
              title,
              summary,
              message: `Please continue implementation as ${nextRole}.`,
              writeSet: [artifactPath],
              dependencies: [],
              acceptance: ["Update artifact and submit final report"],
              artifacts: [artifactPath]
            }
          }
        ]
      : []
  };

  process.stderr.write("model: mock-agent-cli\n");
  process.stderr.write(`role: ${role}\n`);
  process.stderr.write(`next_role: ${nextRole ?? "none"}\n`);

  await postJson(`${managerUrl}/api/projects/${encodeURIComponent(projectId)}/reports`, reportBody);
  process.stdout.write(`${summary}\n`);
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`error: ${message}\n`);
  process.exitCode = 1;
});
